#ifndef DEF_ICE_GLOBALDATA_PRIVATE_H
#define DEF_ICE_GLOBALDATA_PRIVATE_H

#define ICE_GLOBALDATA_WINDOW extern ICE_Window ICE_GLOBJ_WINDOW;
#define ICE_GLOBALDATA_INPUT extern ICE_Input ICE_GLOBJ_INPUT;
#define ICE_GLOBALDATA_RENDERER extern ICE_Renderer ICE_GLOBJ_RENDERER;
#define ICE_GLOBALDATA_SCENE_CURRENT extern ICE_Scene * ICE_GLOBJ_SCENE_CURRENT;
#define ICE_GLOBALDATA_SCENE_MAIN extern ICE_Scene ICE_GLOBJ_SCENE_MAIN;
#define ICE_GLOBALDATA_TEXTUREMANAGER extern ICE_TextureManager ICE_GLOBJ_TEXTUREMANAGER;
#define ICE_GLOBALDATA_CONFIG extern ICE_Config ICE_GLOBJ_CONFIG;
#define ICE_GLOBALDATA_SOUNDMANAGER extern ICE_SoundManager ICE_GLOBJ_SOUNDMANAGER;
#define ICE_GLOBALDATA_MUSICMANAGER extern ICE_MusicManager ICE_GLOBJ_MUSICMANAGER;
#define ICE_GLOBALDATA_DEBUG_LATEDRAW extern void(*ICE_GLOBJ_DEBUG_LATEDRAW)();
#define ICE_GLOBALDATA_RESOURCES extern ICE_Resources ICE_GLOBJ_RESOURCES;

#endif