#ifndef GAME_CONFIG_H
#define GAME_CONFIG_H

#define ICE_CONFIG_EDITORNAME "coldragon"
#define ICE_CONFIG_PRODUCTNAME "test"
#define ICE_CONFIG_TITLE "Test"
#define ICE_CONFIG_WINDOW_W 1280
#define ICE_CONFIG_WINDOW_H 720
#define ICE_CONFIG_WINDOW_ICON "res//img//000-WINDOW_ICON"
#define ICE_CONFIG_RESIZABLE 1
#define ICE_CONFIG_VSYNC 1
#define ICE_CONFIG_GAME_VERSION "0.1a"

#endif